# Generated by Django 6.0.6 on 2026-06-15 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, verbose_name='Nama Penulis')),
            ],
            options={
                'verbose_name': 'Penulis',
                'verbose_name_plural': 'Daftar Penulis',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, verbose_name='Nama Kategori')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Daftar Kategori',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=45, verbose_name='Nama Depan')),
                ('lname', models.CharField(max_length=45, verbose_name='Nama Belakang')),
                ('phone_num', models.CharField(blank=True, max_length=11, null=True, verbose_name='No. Telepon')),
                ('email', models.EmailField(max_length=45, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=45, verbose_name='Password')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
            ],
            options={
                'verbose_name': 'Orang',
                'verbose_name_plural': 'Daftar Orang',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, verbose_name='Nama Penerbit')),
                ('address', models.CharField(blank=True, max_length=45, null=True, verbose_name='Alamat')),
                ('phone_num', models.CharField(blank=True, max_length=11, null=True, verbose_name='No. Telepon')),
            ],
            options={
                'verbose_name': 'Penerbit',
                'verbose_name_plural': 'Daftar Penerbit',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False, verbose_name='ISBN')),
                ('title', models.CharField(max_length=45, verbose_name='Judul Buku')),
                ('publication_year', models.IntegerField(verbose_name='Tahun Terbit')),
                ('selling_price', models.FloatField(verbose_name='Harga Jual')),
                ('min_quantity', models.IntegerField(verbose_name='Stok Minimum')),
                ('page_count', models.IntegerField(verbose_name='Jumlah Halaman')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Stok Saat Ini')),
                ('author', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, related_name='books', to='store.author', verbose_name='Penulis')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='books', to='store.category', verbose_name='Kategori')),
                ('publisher', models.ForeignKey(db_column='publisher_id', on_delete=django.db.models.deletion.CASCADE, related_name='books', to='store.publisher', verbose_name='Penerbit')),
            ],
            options={
                'verbose_name': 'Buku',
                'verbose_name_plural': 'Daftar Buku',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('person', models.OneToOneField(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='manager', serialize=False, to='store.person')),
                ('bonus_level', models.CharField(max_length=10, verbose_name='Level Bonus')),
                ('department', models.CharField(max_length=45, verbose_name='Departemen')),
                ('office_location', models.CharField(max_length=100, verbose_name='Lokasi Kantor')),
                ('hired_date', models.DateField(verbose_name='Tanggal Diterima Kerja')),
            ],
            options={
                'verbose_name': 'Manajer',
                'verbose_name_plural': 'Daftar Manajer',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('person', models.OneToOneField(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='staff', serialize=False, to='store.person')),
                ('role', models.CharField(max_length=30, verbose_name='Peran/Jabatan')),
                ('weekly_hours', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Jam Kerja Mingguan')),
                ('certification_status', models.CharField(blank=True, max_length=45, null=True, verbose_name='Status Sertifikasi')),
            ],
            options={
                'verbose_name': 'Staf',
                'verbose_name_plural': 'Daftar Staf',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.AutoField(primary_key=True, serialize=False)),
                ('sale_time', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Penjualan')),
                ('quantity', models.IntegerField(verbose_name='Jumlah')),
                ('unit_price', models.FloatField(verbose_name='Harga Satuan')),
                ('total_amount', models.FloatField(blank=True, verbose_name='Total Pendapatan')),
                ('book', models.ForeignKey(db_column='isbn', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='store.book', verbose_name='Buku')),
                ('staff', models.ForeignKey(db_column='staff_id', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='store.staff', verbose_name='Staf Penjual')),
            ],
            options={
                'verbose_name': 'Penjualan',
                'verbose_name_plural': 'Daftar Penjualan',
            },
        ),
        migrations.CreateModel(
            name='BookOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Pemesanan')),
                ('quantity', models.IntegerField(verbose_name='Jumlah')),
                ('total_price', models.FloatField(blank=True, verbose_name='Total Harga')),
                ('status', models.CharField(default='Pending', max_length=20, verbose_name='Status')),
                ('book', models.ForeignKey(db_column='isbn', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.book', verbose_name='Buku')),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.person', verbose_name='Pelanggan')),
                ('processed_by_staff', models.ForeignKey(blank=True, db_column='processed_by_staff_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processed_orders', to='store.staff', verbose_name='Staf Pemroses')),
            ],
            options={
                'verbose_name': 'Pemesanan Buku',
                'verbose_name_plural': 'Daftar Pemesanan Buku',
            },
        ),
    ]
